include: package:flutter_lints/flutter.yaml

linter:
  rules:
    omit_local_variable_types: false
    prefer_relative_imports: false
    always_use_package_imports: true
    avoid_returning_null_for_future: true
    avoid_slow_async_io: true
    avoid_type_to_string: true
    no_duplicate_case_values: true
    always_put_required_named_parameters_first: true
    avoid_bool_literals_in_conditional_expressions: true
    avoid_unnecessary_containers: true
    deprecated_consistency: true
    prefer_const_constructors: true
    constant_identifier_names: false